name: dobalito
description: A Flutter application for Android, iOS, and Web platforms

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # HTTP client
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # UI components
  cupertino_icons: ^1.0.2
  
  # Navigation
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true