[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/docker-compose.yml"
buildContext = "docker"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
