[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile.fullstack"
buildContext = "."

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
