name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_URL: https://retsko.ru
  BACKEND_IMAGE: dobalito-backend
  FRONTEND_IMAGE: dobalito-frontend

jobs:
  # --- 1. Проверка и подготовка инфраструктуры ---
  deploy-infrastructure:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy base infrastructure
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 300s
          script: |
            set -e
            sudo mkdir -p /opt/dobalito/docker
            sudo chown $USER:$USER /opt/dobalito
            cd /opt/dobalito

            echo "=== Pulling base images ==="
            docker pull postgres:15-alpine &
            docker pull nginx:alpine &
            wait

            echo "=== Starting DB and Nginx ==="
            docker compose -f docker/docker-compose.prod.yml up -d postgres nginx

            sleep 10
            echo "=== Checking DB existence ==="
            docker exec -e PGPASSWORD=${{ env.POSTGRES_PASSWORD }} dobalito-postgres \
              psql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='dobalito'" | grep -q 1 || \
              docker exec -e PGPASSWORD=${{ env.POSTGRES_PASSWORD }} dobalito-postgres \
              psql -U postgres -c "CREATE DATABASE dobalito;"

  # --- 2. Проверяем миграции Flyway ---
  test-migrations:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Repair Flyway schema history
        run: |
          docker run --rm \
            -v $PWD/backend/src/main/resources/db/migration:/flyway/sql \
            flyway/flyway:9-alpine \
            -url=jdbc:postgresql://${{ secrets.SERVER_HOST }}:5432/dobalito \
            -user=postgres \
            -password=${{ secrets.POSTGRES_PASSWORD }} \
            repair

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            -v $PWD/backend/src/main/resources/db/migration:/flyway/sql \
            flyway/flyway:9-alpine \
            -url=jdbc:postgresql://${{ secrets.SERVER_HOST }}:5432/dobalito \
            -user=postgres \
            -password=${{ secrets.POSTGRES_PASSWORD }} \
            migrate

  # --- 3. Сборка backend ---
  build-backend:
    runs-on: ubuntu-latest
    needs: test-migrations
    outputs:
      image: ${{ steps.meta.outputs.tags }}
      changed: ${{ steps.backend-changes.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Нужно для сравнения с предыдущим коммитом
      
      - name: Check for backend changes
        id: backend-changes
        run: |
          # Проверяем, есть ли предыдущий коммит
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            if git diff --quiet HEAD~1 HEAD -- backend/ docker/Dockerfile.backend docker/docker-compose*.yml; then
              echo "changed=false" >> $GITHUB_OUTPUT
              echo "No backend changes detected, skipping build"
            else
              echo "changed=true" >> $GITHUB_OUTPUT
              echo "Backend changes detected, will build"
            fi
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "First commit detected, will build"
          fi
      
      - uses: docker/setup-buildx-action@v3
      - run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set metadata
        id: meta
        if: steps.backend-changes.outputs.changed == 'true'
        uses: docker/metadata-action@v5
        with:
          images: retsko.ru/${{ env.BACKEND_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & Push Backend
        if: steps.backend-changes.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=dobalito-backend
          cache-to: type=gha,scope=dobalito-backend,mode=max

  # --- 4. Сборка frontend ---
  build-frontend:
    runs-on: ubuntu-latest
    needs: test-migrations
    outputs:
      image: ${{ steps.meta.outputs.tags }}
      changed: ${{ steps.frontend-changes.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Нужно для сравнения с предыдущим коммитом
      
      - name: Check for frontend changes
        id: frontend-changes
        run: |
          # Проверяем, есть ли предыдущий коммит
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            if git diff --quiet HEAD~1 HEAD -- frontend-react/ docker/Dockerfile.frontend-react docker/nginx-react.conf; then
              echo "changed=false" >> $GITHUB_OUTPUT
              echo "No frontend changes detected, skipping build"
            else
              echo "changed=true" >> $GITHUB_OUTPUT
              echo "Frontend changes detected, will build"
            fi
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "First commit detected, will build"
          fi
      
      - uses: docker/setup-buildx-action@v3
      - run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set metadata
        id: meta
        if: steps.frontend-changes.outputs.changed == 'true'
        uses: docker/metadata-action@v5
        with:
          images: retsko.ru/${{ env.FRONTEND_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & Push Frontend
        if: steps.frontend-changes.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend-react
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,scope=dobalito-frontend
          cache-to: type=gha,scope=dobalito-frontend,mode=max

  # --- 5. Деплой ---
  deploy-applications:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Check if deployment needed
        id: deploy-needed
        run: |
          if [[ "${{ needs.build-backend.outputs.changed }}" == "true" || "${{ needs.build-frontend.outputs.changed }}" == "true" ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
            echo "Changes detected, deployment needed"
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
            echo "No changes detected, skipping deployment"
          fi

      - name: Deploy to server
        if: steps.deploy-needed.outputs.deploy == 'true'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 300s
          script: |
            set -e
            cd /opt/dobalito

            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login retsko.ru -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

            echo "=== Repairing Flyway schema history ==="
            docker run --rm \
              -v /opt/dobalito/backend/src/main/resources/db/migration:/flyway/sql \
              flyway/flyway:9-alpine \
              -url=jdbc:postgresql://localhost:5432/dobalito \
              -user=postgres \
              -password="${{ secrets.POSTGRES_PASSWORD }}" \
              repair

            echo "=== Pulling latest images ==="
            docker compose -f docker/docker-compose.prod.yml pull --parallel backend frontend-react

            echo "=== Restarting containers ==="
            docker compose -f docker/docker-compose.prod.yml up -d backend frontend-react

            echo "=== Checking health ==="
            docker ps --filter "name=dobalito"
            curl -f http://localhost:8080/api/v1/auth/test || echo "Backend health check failed"
            curl -f http://localhost:3000 || echo "Frontend health check failed"

      - name: Notify status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi
